name: pagepals
description: A PagePals app for Flutter.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:
  page_transition:
  flutter_chat_ui:
  file_picker:
  image_picker:
  http: ^1.2.0
  uuid:
  open_filex:
  path_provider:
  zego_uikit_prebuilt_video_conference: ^2.6.9
  flutter_dotenv: ^5.1.0
  dropdown_button2: ^2.3.8
  flutter_verification_code_field: ^1.0.4
  video_player: ^2.8.2
  chewie: ^1.7.4
  graphql_flutter: ^5.2.0-beta.6
  quickalert: ^1.0.2
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  easy_date_timeline: ^1.0.3
  intl: ^0.18.1
  provider:
  google_fonts: ^6.2.1
  flutter_switch: ^0.3.2
  unicons: ^2.1.1
  custom_refresh_indicator: ^3.0.0
  shared_preferences:
  animated_text_kit: ^4.2.2
  flutter_carousel_widget: ^2.2.0
  flutter_localizations:
    sdk: flutter
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - .env
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf