name: pagepals
description: A PagePals app for Flutter.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter:
  page_transition:
  flutter_chat_ui:
  file_picker:
  image_picker:
  http: ^1.2.0
  uuid:
  open_filex:
  path_provider:
  zego_uikit_prebuilt_video_conference: ^2.6.9
  flutter_dotenv: ^5.1.0
  dropdown_button2: ^2.3.8
  flutter_verification_code_field: ^1.0.4
  video_player: ^2.8.2
  chewie: ^1.7.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env