name: pagepals
description: A PagePals app for Flutter.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter:
  page_transition:
  flutter_chat_ui:
  file_picker:
  image_picker:
  uuid:
  open_filex:
  path_provider:
  zego_uikit_prebuilt_video_conference: ^2.6.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/