name: pagepals
description: A PagePals app for Flutter.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter:
  page_transition:
  flutter_chat_ui:
  file_picker:
  image_picker:
  http: ^1.2.0
  uuid:
  open_filex:
  path_provider:
  zego_uikit_prebuilt_video_conference: ^2.6.9
  flutter_dotenv: ^5.1.0
  dropdown_button2: ^2.3.8
  flutter_verification_code_field: ^1.0.4
  video_player: ^2.8.2
  chewie: ^1.7.4
  graphql_flutter: ^5.2.0-beta.6
  quickalert: ^1.0.2
  google_sign_in: ^6.2.1
  firebase_auth: ^4.17.6
  firebase_core: ^2.25.5
  firebase_storage: ^11.6.10
  cloud_firestore: ^4.15.9
  firebase_messaging: ^14.7.20
  flutter_local_notifications:
  easy_date_timeline: ^1.0.3
  intl: ^0.18.1
  provider:
  google_fonts: ^6.2.1
  flutter_switch: ^0.3.2
  unicons: ^2.1.1
  custom_refresh_indicator: ^3.0.0
  shared_preferences:
  animated_text_kit: ^4.2.2
  flutter_carousel_widget: ^2.2.0
  comment_tree: ^0.3.0
  easy_stepper: ^0.8.3
  shimmer: ^3.0.0
  dart_jsonwebtoken: ^2.13.0
  loading_animation_widget: ^1.2.1
  encrypt: ^5.0.3
  url_launcher: ^6.2.5
  fl_chart: ^0.66.2
  flutter_slidable: ^3.1.0
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_lints: ^2.0.0
  mobkit_dashed_border: ^0.0.6

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - .env
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf